version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      - USE_LOCAL_DB=true
      - AWS_REGION=us-east-1
      # Point AWS SDK to local DynamoDB
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local
    restart: unless-stopped

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-inMemory']
